language: objc

osx_image: xcode12.5
env:
  matrix:
    - TEST_SDK=iphonesimulator14.5 OS=12.5 NAME='iPhone XR'

script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -project MemoryLeak.xcodeproj -scheme MemoryLeak -sdk $TEST_SDK -destination "platform=iOS Simulator,OS=$OS,name=$NAME" ONLY_ACTIVE_ARCH=YES

after_success:
  - slather
  - bash <(curl -s https://codecov.io/bash) -f reports/cobertura.xml -X coveragepy -X gcov -X xcode

